[app]
name = "mulemail"
version = "0.1.0"
license = "GLPv3"
author = "Immanuel Stemmert"

[meta]
repo = 'https://github.com/bertrandterrier/mulemail'
homepage = false
contact = 'mail(at)immanuelstemmert.de'
created = 2025-10-18
update = 2025-10-18
